# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5455e903cb857e72497feb1f66720bafabb6da052de13252a8e66bfd6f164745c580bca95eba0811deaa3b4e215544241bc17e0b2663f8cb390c8c5c33475726

test:
  secret_key_base: 13315b1cdb1ef37d4421338d95eeee12848063820a558d2adb3457e2a9ae757005fec8338611dacc2ccb1ded24533dcf3543dbb54aec620eecda02ba8b880c47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
